[package]
name = "cipherwhisper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "cipherwhisper"

[[bin]]
name = "cipherwhisper"
path = "src/main.rs"

[[bin]]
name = "cipherwhisper-desktop"
path = "src/bin/cipherwhisper-desktop.rs"
test = false
bench = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
cipherwhisper-cli.workspace = true
cipherwhisper-domain.workspace = true
cipherwhisper-relay.workspace = true
cipherwhisper-protocol.workspace = true
cipherwhisper-core.workspace = true
rcgen.workspace = true
zeroize = "1"
time = "0.3"
reqwest.workspace = true
getrandom = "0.4"
hex.workspace = true
uuid.workspace = true
serde.workspace = true
axum.workspace = true
subtle = "2"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
tao = "0.37.1"
wry = "0.57.0"
tray-icon = "0.26.0"
rfd = "0.17.2"
